menu:
  #Archives: /archives
  黄金屋: /favourite
  时光机: /favourite/time.html
  #我是: /aboutme

# rss需安装插件hexo-generator-feed，详细请看：https://monniya.com/2016/02/24/create-rss/
# rss: /atom.xml
# description配置内容会出现在meta标签中，因此会被搜索引擎抓取
description: 

# 不填写的链接则不显示
social:
  weibo: https://weibo.com/monniya
  github: https://github.com/monniya
  stack_overflow: 
  facebook: 
  twitter: 
  google_plus: 

page_comment: true

# 封面中的头像
logo: /images/favicon.jpg
background:
  cover: /images/background-cover.jpg
  color: cover-purple

archive_date_format: MMM DD
fancybox: true

# 多说的帐号名, 不配置则不启用，使用disqus请去全局_config.yml中配置disqus_shortname
duoshuo_shortname: 

google_analytics: 谷歌跟踪ID
baidu_tongji: 百度统计识别码
favicon: /images/avatar-small.png
